use crate::common::types::Waypoint;
use revm::primitives::U256;
use z3::ast::{Ast, BV};
use z3::{Config, Context, Solver};

/// ConcolicSolver leverages Z3 to solve for input values that satisfy 
/// branching conditions encountered during execution.
pub struct ConcolicSolver<'a> {
    ctx: &'a Context,
}

impl<'a> ConcolicSolver<'a> {
    pub fn new(ctx: &'a Context) -> Self {
        Self { ctx }
    }

    /// Generates a "hint" (a 32-byte value) that would satisfy the alternative 
    /// path of a comparison.
    pub fn solve_hint(&self, waypoint: &Waypoint) -> Option<[u8; 32]> {
        if let Waypoint::Comparison { op, lhs, rhs, calldata_offset, .. } = waypoint {
            if calldata_offset.is_none() {
                return None;
            }

            let cfg = Config::new();
            let solver = Solver::new(self.ctx);

            // Represent the tainted input as a 256-bit bit-vector
            let input_var = BV::new_const(self.ctx, "input_var", 256);
            
            // Convert operands to Z3 constants
            let lhs_const = BV::from_u64(self.ctx, 0, 256); // Placeholder logic
            let rhs_val = self.u256_to_bv(rhs);
            let lhs_val = self.u256_to_bv(lhs);

            // We assume one side was influenced by calldata. 
            // We constrain the variable to satisfy the comparison op.
            let constraint = match *op {
                0x10 => input_var.bvult(&rhs_val), // LT
                0x11 => input_var.bvugt(&rhs_val), // GT
                0x14 => input_var._eq(&rhs_val),   // EQ
                0x12 => input_var.bvslt(&rhs_val), // SLT
                0x13 => input_var.bvsgt(&rhs_val), // SGT
                _ => return None,
            };

            solver.assert(&constraint);

            if solver.check() == z3::SatResult::Sat {
                let model = solver.get_model().unwrap();
                let solution = model.eval(&input_var, true).unwrap();
                return Some(self.bv_to_bytes(solution));
            }
        }
        None
    }

    fn u256_to_bv(&self, val: &U256) -> BV<'a> {
        let bytes = val.to_be_bytes::<32>();
        let mut hex = String::from("0x");
        for b in bytes {
            hex.push_str(&format!("{:02x}", b));
        }
        BV::from_str(self.ctx, 256, &hex).unwrap()
    }

    fn bv_to_bytes(&self, bv: BV<'a>) -> [u8; 32] {
        let mut bytes = [0u8; 32];
        let bit_string = format!("{:x}", bv); // Z3 returns hex
        let stripped = bit_string.trim_start_matches("0x");
        let decoded = hex::decode(format!("{:0>64}", stripped)).unwrap();
        bytes.copy_from_slice(&decoded);
        bytes
    }
}

/// Extends the EvmInput with hints generated by the Concolic engine.
pub struct ConcolicHint {
    pub offset: usize,
    pub value: [u8; 32],
}