use crate::common::oracle::VulnType;
use crate::common::types::Snapshot;
use chrono::Utc;
use serde::{Serialize, Deserialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VulnerabilityReport {
    pub timestamp: String,
    pub snapshot_id: u64,
    pub vuln_type: VulnType,
    pub description: String,
    pub severity: Severity,
    pub poc_transactions: Vec<String>,
    pub economic_impact: Option<EconomicImpact>,
    pub recommended_mitigation: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum Severity {
    Critical,
    High,
    Medium,
    Low,
    Informational,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EconomicImpact {
    pub estimated_loss_eth: f64,
    pub affected_protocols: Vec<String>,
    pub attack_complexity: String,
}

impl VulnerabilityReport {
    pub fn new(
        snapshot: &Snapshot,
        vuln_type: VulnType,
        description: String,
        poc_transactions: Vec<String>,
    ) -> Self {
        let severity = Self::classify_severity(&vuln_type);
        
        Self {
            timestamp: Utc::now().to_rfc3339(),
            snapshot_id: snapshot.id,
            vuln_type,
            description,
            severity,
            poc_transactions,
            economic_impact: None,
            recommended_mitigation: None,
        }
    }

    fn classify_severity(vuln_type: &VulnType) -> Severity {
        match vuln_type {
            VulnType::Reentrancy => Severity::Critical,
            VulnType::FlashLoanProfit => Severity::Critical,
            VulnType::PriceOracleManipulation => Severity::High,
            VulnType::IntegerOverflow => Severity::High,
            VulnType::Other(msg) if msg.contains("AccessControl") => Severity::High,
            _ => Severity::Medium,
        }
    }

    pub fn with_economic_impact(mut self, impact: EconomicImpact) -> Self {
        self.economic_impact = Some(impact);
        self
    }

    pub fn with_mitigation(mut self, mitigation: String) -> Self {
        self.recommended_mitigation = Some(mitigation);
        self
    }

    /// Generate Foundry script for reproducing the vulnerability
    pub fn generate_foundry_script(&self) -> String {
        let mut script = format!(
            "// SPDX-License-Identifier: MIT\n\
             pragma solidity ^0.8.19;\n\n\
             import \"forge-std/Script.sol\";\n\n\
             /// @title Vulnerability PoC - {}\n\
             /// @notice Generated by RustyFuzz on {}\n\
             contract {}PoC is Script {{\n\
             \n    function run() external {{\n",
            self.description,
            self.timestamp,
            match self.vuln_type {
                VulnType::Reentrancy => "Reentrancy",
                VulnType::FlashLoanProfit => "FlashLoan",
                VulnType::PriceOracleManipulation => "PriceManipulation",
                _ => "Vulnerability",
            }
        );

        for (i, tx) in self.poc_transactions.iter().enumerate() {
            script.push_str(&format!(
                "\n        // Transaction {}\n        vm.broadcast();\n        // Calldata: {}\n",
                i + 1,
                tx
            ));
        }

        script.push_str("\n    }\n}\n");
        script
    }

    /// Save report to JSON file
    pub fn save_to_file(&self, path: &str) -> std::io::Result<()> {
        use std::fs::File;
        use std::io::Write;
        
        let json = serde_json::to_string_pretty(self)?;
        let mut file = File::create(path)?;
        file.write_all(json.as_bytes())?;
        Ok(())
    }
}

/// Summary statistics for a fuzzing campaign
#[derive(Debug, Default, Serialize, Deserialize)]
pub struct CampaignSummary {
    pub total_executions: u64,
    pub unique_paths_found: u64,
    pub vulnerabilities_discovered: u64,
    pub corpus_size: u64,
    pub avg_gas_per_tx: u64,
    pub execution_time_secs: u64,
    pub execs_per_second: f64,
}

impl CampaignSummary {
    pub fn print_report(&self) {
        println!("\n📊 Fuzzing Campaign Summary");
        println!("   Total Executions: {}", self.total_executions);
        println!("   Unique Paths: {}", self.unique_paths_found);
        println!("   Vulnerabilities: {}", self.vulnerabilities_discovered);
        println!("   Corpus Size: {}", self.corpus_size);
        println!("   Avg Gas/Tx: {}", self.avg_gas_per_tx);
        println!("   Duration: {}s", self.execution_time_secs);
        println!("   Execs/sec: {:.2}", self.execs_per_second);
    }
}